/*
**      key.h
*/

#ifndef __KEY__
    #define __KEY__

/*============== key code =================*/

    #define F1              0x3B00
    #define F2              0x3C00
    #define F3              0x3D00
    #define F4              0x3E00
    #define F5              0x3F00
    #define F6              0x4000
    #define F7              0x4100
    #define F8              0x4200
    #define F9              0x4300
    #define F10             0x4400
    #define DEL             0x5300

    #define HOME    0x4700
    #define END             0x4f00
    #define PAGEUP  0x4900
    #define PAGEDWN 0x5100

    #define AUP             0x4800     /* arrow key                           */
    #define ADOWN   0x5000
    #define ARIGHT  0x4D00
    #define ALEFT   0x4B00

/* key code */
    #define STX             0x02
    #define ETX             0x03
    #define ENQ             0x05
    #define ACK             0x06
    #define BS              0x08
    #define TAB             0x09
    #define CR              0x0D
    #define NAK             0x15
    #define CAN             0x18
    #define ESC             0x1B
    #define SPACE   0x20
/*=========================================*/

#endif

/*** end of key.h ***/
